import { PageTemplate, Dishe } from "@/components";
import type { NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate>
      <h1>Encontre opções em Delivery próximos à você.</h1>

      <h2>
          Descubra seu novo Delivery favorito. Milhares de opções a um clique.
        </h2>
        <Dishe />
      </PageTemplate>
    </>
  );
};
export default Home;
